### PR TITLE
Add missing "to" word in doc

### PR DESCRIPTION
**Pull request by pombredanne**
This is a minor fix to correct an otherwise nonsensical sentence.

Signed-off-by: Philippe Ombredanne <pombredanne@nexb.com>

### CODE REVIEW

**Comment by BurntSushi** [comment]
Thanks, but I'm going to be landing a big change soonish that rewrites a lot of stuff, and would prefer not to have any more changes to the existing code.

**Comment by pombredanne** [comment]
That works! You rock BTW. I was just re-reading your post at https://blog.burntsushi.net/foss/ and I realized how much I am unable to say no most of the time on my own projects and that I should really learn from you more.

**Comment by BurntSushi** [comment]
@pombredanne Thanks. :) And yeah, "no" is important for me to keep a healthy balance with FOSS. Otherwise it's just an avalanche. And also not feeling _too_ bad about the size of my email inbox at the moment... :)

**Comment by pombredanne** [comment]
Guess what: I really enjoyed being said "no" today :)

**Pull request closed without merging**
